CREATE TABLE USER
(
    ID              VARCHAR(50) NOT NULL PRIMARY KEY,
    FIRST_NAME      VARCHAR(50) NOT NULL,
    LAST_NAME       VARCHAR(50) NOT NULL,
    USERNAME        VARCHAR(50) NOT NULL,
    PASSWORD        VARCHAR(50) NOT NULL,
    EMAIL           VARCHAR(255) NOT NULL,
    PHONE_NUMBER    VARCHAR(50),
    ADDRESS         VARCHAR(255),
    CITY            VARCHAR(255),
    STATE           VARCHAR(2),
    ZIP_CODE        VARCHAR(10),
    STATUS          VARCHAR(255) NOT NULL,
    CREATED_DATE    DATETIME NOT NULL,
    UPDATED_DATE    DATETIME NOT NULL
);

CREATE TABLE EMAIL
(
    ID              VARCHAR(50) NOT NULL PRIMARY KEY,
    RECIPIENT       VARCHAR(100) NOT NULL,
    SENDER          VARCHAR(100) NOT NULL,
    CREATED_DATE    DATETIME NOT NULL,
    UPDATED_DATE    DATETIME NOT NULL
)