server:
  port: 8080

spring:
  # All queries executed by the database will be printed to the console.
  jpa:
    show-sql: true
  # See table in the in-memory database by launching h2 console in the browser
  # localhost:8080/h2-console (change JDBC URL to jdbc:h2:mem:testdb)
  h2:
    console:
      enabled: true
  # Reconfiguring H2 Console
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "devorahMailServerUsername"
    password: "devorahMailServerPassword"

# Used for Creating Database Tables in Spring Boot Version > 2.5.0
#spring.jpa.defer-datasource-initialization=true

mail:
  external:
    ip: "https://ti-timeserver.herokuapp.com/api/v1/email/receiveExternalMail"
    apiKey: "letMeIn"